### ISSUE TITLE
USB DVD drive doesn't play

### ISSUE THREAD

**Issue by Bleep42** [FiveNinjas/SliceOS#4]
I've tried to play a standard DVD from a USB DVD drive, I have set the system to auto play disks. 
When I insert the disk, the drive clicks around for a while, a disk icon appears on the screen, but nothing happens and the drive just continues clicking until I eject the disk.

**Comment by ghollingworth** [comment]
This was a license issue which should be fixed by updating from the nightly build, can you test and close?

**Comment by Bleep42** [comment]
I'm still checking this out, it isn't anything to do with the licences as I had corrected them and the problem was still present. I've now put 20150327072056 on and it is still playing up. However I have found If I unplug my usb keyboard, or try using a different usb wifi dongle I can get it to work, but it's unreliable, as in it'll only work say 1 time in 3 times. I'm looking at generating a log file see what that says. Kevin.

**Comment by Bleep42** [comment]
Hi Gordon,
Two log files here https://www.dropbox.com/sh/xvjtrolfaz0c9gz/AABwHlJi-mnlfETLrdJzICb-a?dl=0
The first is trying to play a DVD disk with a USB keyboard plugged into the slice, it always fails, as per the description in my initial comment. I insert the disk around at 11:29. I also get exactly the same, if I use a different WiFi dongle to the one you supplied, with or without the keyboard.
The second log file is with the USB keyboard removed, I have to have 3 attempts at playing the disk, starting at 11:41 what happens is the disk will spin up and down a couple of times accompanied by the usual clicking, it eventually seems to just stop, so I eject the disk and try again, same thing, eject disk again and this time after lots of spinning and clicking it eventually starts playing the disk.
In both logs I initially play an MP4 file from the Slices internal disk, which plays fine.
The DVD is Samsung USB 2.0 External DVD Writer SE-208DB/TSBS as recommended by Mo. It works perfectly on my main PC and it also worked fine on my previous RaspBMC.
http://www.dabs.com/products/samsung-usb-2-0-slim-external-dvd-writer-black-8F6V.html
Hope this is of help.
Regards, Kevin.

**Comment by ghollingworth** [comment]
Kevin,

Are you powering the DVD drive from an external power supply?

The one I've got on my desk takes a peak of around 2A when spinning up (just a little bit over the rated max for the USB connector!)

Gordon

**Comment by Bleep42** [comment]
Hi Gordon,
I just got your reply as I was adding info about the drive above. I don't use an external supply, I'll give it a try and report back. I'm going to have to make up a cable to do this as the DVD doesn't have a separate power input. What I can say, is that it worked fine on a Raspberry Pi Mk1 256Mb memory, one of the original ones, with a WiFi dongle, keyboard, USB memory stick, all plugged in to it as well using an unpowered hub. though I do admit to linking out both F1 and F2.

**Comment by Bleep42** [comment]
Hi Gordon,
I got round the power cable problem by using a powered (3A) hub to drive only the DVD, that does seem to have cured the first log file problem, but the second log file is still valid, it's taking multiple attempts to get the DVD to play, I've tried several different discs as well to be sure it's not the disk itself. More info and a link about the DVD drive added in above comment.
Regards, Kevin.

**Comment by Bleep42** [comment]
Hi Gordon, 
I've now made up a powered USB cable for my USB DVD drive. I'm still having problems playing a DVD.
What usually happens is I put the disk in, it's recognised, but it does not play. If I go to the disk icon which has appeared in the main menu and select play, the Slice lights behave as though it's started, but nothing happens, if I select play again, same thing happens. Then I eject the disk and re-insert it, this time, usually, it will play, though this is not a certainty. I have tried this via a 'un-powered' USB hub, a 'powered' USB hub and directly connected to the Slice. The results all seem to be the same.
If you look in the logs and search for 'Error cracking CSS key' this seems to be the problem, as when I insert the disk the second time I no longer get these errors.
https://www.dropbox.com/sh/ulvcmkbwofwtbwa/AAD0CPWSbOf6vOWLPdaHKW3wa?dl=0
Regards, Kevin.
